
CREATE DATABASE bamazon_db;

USE bamazon_db;

CREATE TABLE products (
item_id INT (2) NOT NULL AUTO_INCREMENT,
product_name VARCHAR(50) NOT NULL,
department_name VARCHAR(50) NOT NULL,
price DECIMAL (10,2) NOT NULL,
stock_quantity INT(5) NOT NULL,
PRIMARY KEY(item_id)

);

INSERT INTO products ( product_name,department_name,price,stock_quantity)
VALUES
("GOODNIGHT MOON","CHILDRENS BOOK",10.00,50),
("CLASSIC QUILTED JACKET","CLOTHING",50.00,60),
("XBOX","GAMING",200.00,30),
("ORGANIC CREAMY PEANUT BUTTER","FOOD",20.00,40),
("ORGANIC COCONUT OIL","FOOD",20.00,50),
("MICROWAVE","APPLIANCES",60.00,20),
("NECKLASE","JEWELLARY",30.00,50),
("BRACELET","JEWELLARY",35.00,40),
("STROLLER","KIDS",100.00,50),
("DIAPERS","KIDS",10.99,60);

SELECT * FROM products;
